---
inherit_from:
  - https://raw.githubusercontent.com/riboseinc/oss-guides/master/ci/rubocop.yml

Layout/SpaceAroundOperators:
  Exclude:
    - Formula/rnp.rb

Layout/LineLength:
  Exclude:
    - Formula/rnp.rb
